# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='ImageInfo',
  serialized_pb=_b('\n\ntest.proto\x12\tImageInfo\"\xac\x02\n\nimage_info\x12\x12\n\nimage_data\x18\x01 \x03(\r\x12\x31\n\ttask_type\x18\x02 \x02(\x0e\x32\x1e.ImageInfo.image_info.Tasktype\x12\x13\n\x0bimage_width\x18\x03 \x02(\x05\x12\x14\n\x0cimage_height\x18\x04 \x02(\x05\x12\x12\n\nimage_name\x18\x05 \x02(\t\x12\x12\n\nmodel_name\x18\x06 \x01(\t\x12\x1a\n\x12image_valid_height\x18\x07 \x01(\x05\x12\x19\n\x11image_valid_width\x18\x08 \x01(\x05\"M\n\x08Tasktype\x12\x12\n\x0e\x63lassification\x10\x00\x12\r\n\tdetection\x10\x01\x12\x10\n\x0csegmentation\x10\x02\x12\x0c\n\x08instance\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_IMAGE_INFO_TASKTYPE = _descriptor.EnumDescriptor(
  name='Tasktype',
  full_name='ImageInfo.image_info.Tasktype',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='classification', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='detection', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='segmentation', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='instance', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=249,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_IMAGE_INFO_TASKTYPE)


_IMAGE_INFO = _descriptor.Descriptor(
  name='image_info',
  full_name='ImageInfo.image_info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='ImageInfo.image_info.image_data', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_type', full_name='ImageInfo.image_info.task_type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_width', full_name='ImageInfo.image_info.image_width', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='ImageInfo.image_info.image_height', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_name', full_name='ImageInfo.image_info.image_name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_name', full_name='ImageInfo.image_info.model_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_valid_height', full_name='ImageInfo.image_info.image_valid_height', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image_valid_width', full_name='ImageInfo.image_info.image_valid_width', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGE_INFO_TASKTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=326,
)

_IMAGE_INFO.fields_by_name['task_type'].enum_type = _IMAGE_INFO_TASKTYPE
_IMAGE_INFO_TASKTYPE.containing_type = _IMAGE_INFO
DESCRIPTOR.message_types_by_name['image_info'] = _IMAGE_INFO

image_info = _reflection.GeneratedProtocolMessageType('image_info', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE_INFO,
  __module__ = 'test_pb2'
  # @@protoc_insertion_point(class_scope:ImageInfo.image_info)
  ))
_sym_db.RegisterMessage(image_info)


# @@protoc_insertion_point(module_scope)
