/*!
 * -------------------------------------------
 * Copyright (c) 2019, Horizon Robotics, Inc.
 * All rights reserved.
 * \File     uws_server.h
 * \Author   ronghui.zhang 
 * \Version  1.0.0.0
 * \Date     2020/05/12
 * \Brief    implement of uws_server.h
 * \DO NOT MODIFY THIS COMMENT, \
 * \WHICH IS AUTO GENERATED BY EDITOR
 * -------------------------------------------
 */
#ifndef _J5_SAMPLE_INCLUDE_UWS_SERVER_H_
#define _J5_SAMPLE_INCLUDE_UWS_SERVER_H_
#include <memory>
#include <string>
#include <thread>

#include "uWS/uWS.h"
#include "thread_pool.h"

namespace J5Sample {
using J5Sample::CThreadPool;

class UwsServer {
 public:
  explicit UwsServer(const std::string &config);
  UwsServer() : connetion_(nullptr), worker_(nullptr) {}
  ~UwsServer() = default;

 public:
  int Init();
  int Send(const std::string &protocol);
  int DeInit();

 private:
  void StartServer();
  std::mutex mutex_;
  uWS::WebSocket<uWS::SERVER> *connetion_;
  std::shared_ptr<std::thread> worker_;
 private:
  std::string config_file_;
};
}  // namespace J5Sample

#endif  // _J5_SAMPLE_INCLUDE_UWS_SERVER_H_
